# Generated by Django 3.0.6 on 2020-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptdjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
