# Generated by Django 3.0.6 on 2020-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptdjango', '0003_order_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing Transaction', 'Processing Transaction'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
