# Generated by Django 3.0.6 on 2020-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptdjango', '0007_auto_20200518_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='title',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
