# Generated by Django 3.0.6 on 2020-05-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptdjango', '0008_auto_20200518_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
