# Generated by Django 3.0.6 on 2020-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptdjango', '0009_auto_20200518_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profitmargin',
            field=models.FloatField(default=20, null=True),
        ),
    ]
